# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 380)
        Dialog.setMinimumSize(QtCore.QSize(700, 380))
        Dialog.setMaximumSize(QtCore.QSize(700, 380))
        Dialog.setSizeIncrement(QtCore.QSize(700, 380))
        self.Button_clear_Symbols = QtWidgets.QPushButton(Dialog)
        self.Button_clear_Symbols.setGeometry(QtCore.QRect(380, 350, 101, 25))
        self.Button_clear_Symbols.setObjectName("Button_clear_Symbols")
        self.Button_clear_english = QtWidgets.QPushButton(Dialog)
        self.Button_clear_english.setGeometry(QtCore.QRect(270, 350, 111, 25))
        self.Button_clear_english.setObjectName("Button_clear_english")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 681, 301))
        self.plainTextEdit.setMaximumSize(QtCore.QSize(700, 400))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Button_Erase = QtWidgets.QPushButton(Dialog)
        self.Button_Erase.setGeometry(QtCore.QRect(410, 320, 81, 25))
        self.Button_Erase.setObjectName("Button_Erase")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(490, 320, 81, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(570, 320, 81, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 320, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_swap_words = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_swap_words.setGeometry(QtCore.QRect(120, 320, 141, 25))
        self.lineEdit_swap_words.setInputMask("")
        self.lineEdit_swap_words.setText("")
        self.lineEdit_swap_words.setPlaceholderText("")
        self.lineEdit_swap_words.setObjectName("lineEdit_swap_words")
        self.Button_Limit_words = QtWidgets.QPushButton(Dialog)
        self.Button_Limit_words.setGeometry(QtCore.QRect(10, 350, 111, 25))
        self.Button_Limit_words.setObjectName("Button_Limit_words")
        self.spinBox_limit_wrods = QtWidgets.QSpinBox(Dialog)
        self.spinBox_limit_wrods.setGeometry(QtCore.QRect(120, 349, 141, 27))
        self.spinBox_limit_wrods.setObjectName("spinBox_limit_wrods")
        self.Button_Resize_spaces = QtWidgets.QPushButton(Dialog)
        self.Button_Resize_spaces.setEnabled(True)
        self.Button_Resize_spaces.setGeometry(QtCore.QRect(480, 350, 101, 25))
        self.Button_Resize_spaces.setObjectName("Button_Resize_spaces")
        self.Button_clear_Numbers = QtWidgets.QPushButton(Dialog)
        self.Button_clear_Numbers.setEnabled(True)
        self.Button_clear_Numbers.setGeometry(QtCore.QRect(580, 350, 111, 25))
        self.Button_clear_Numbers.setObjectName("Button_clear_Numbers")
        self.Button_Add_Dot = QtWidgets.QPushButton(Dialog)
        self.Button_Add_Dot.setGeometry(QtCore.QRect(330, 320, 81, 25))
        self.Button_Add_Dot.setObjectName("Button_Add_Dot")

        self.retranslateUi(Dialog)
        self.Button_Erase.clicked.connect(self.plainTextEdit.clear)
        self.pushButton_5.clicked.connect(self.plainTextEdit.paste)
        self.pushButton_4.clicked.connect(self.plainTextEdit.selectAll)
        self.pushButton_4.clicked.connect(self.plainTextEdit.copy)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Button_clear_Symbols.setText(_translate("Dialog", "Clear symbols"))
        self.Button_clear_english.setText(_translate("Dialog", "Clear English"))
        self.Button_Erase.setText(_translate("Dialog", "Earse"))
        self.pushButton_4.setText(_translate("Dialog", "Copy"))
        self.pushButton_5.setText(_translate("Dialog", "Paste"))
        self.pushButton.setText(_translate("Dialog", "Swap words"))
        self.lineEdit_swap_words.setToolTip(_translate("Dialog", "Enter number swap word with spase like 1 8 9"))
        self.Button_Limit_words.setText(_translate("Dialog", "Limit word"))
        self.Button_Resize_spaces.setText(_translate("Dialog", "Resize spaces"))
        self.Button_clear_Numbers.setText(_translate("Dialog", "Clear Numbers"))
        self.Button_Add_Dot.setText(_translate("Dialog", "Dot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
